# Generated by Django 4.1 on 2022-09-02 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('st_bp', models.IntegerField()),
                ('dy_bp', models.IntegerField()),
                ('chol', models.IntegerField()),
                ('gluc', models.IntegerField()),
                ('smoke', models.IntegerField()),
                ('alco', models.IntegerField()),
                ('active', models.IntegerField()),
                ('cardio', models.IntegerField()),
                ('medication', models.CharField(max_length=1)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_date', models.DateField()),
                ('steps', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.member')),
            ],
        ),
    ]
