# Generated by Django 4.1 on 2022-09-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_member_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
